### ISSUE TITLE
File Renaming - Implementation Plan

### ISSUE THREAD

**Issue by Nuno-Ferreira** [Nuno-Ferreira/File_Renaming_APP#1]
**Implementation for the File Renaming Application**

To set up this application, the development of it needs to be broken down into 3 major stages:

- [ ] Application Logic (set up the processing/logic of the application to change file names)
- [ ] Application GUI (set up the graphical user interface for this application for all OS)
- [ ] Build/Package Application (build/package the application to be able to release the app to the public)
